Mobile and other knits
sabineloos/lab-site pull request #8
Opened 2023-01-02 18:49 UTC by margueriteroth

Hola!

* adjusted content to collapse on narrower widths
* swapped out `<a href..`> to use the `<Link>` component (which will handle the target noref things!)
* cleaned up the `<MaxWidth>` usage — that also has some pre-canned widths and padding.
* 
xoxoxo

2023-01-03 15:57 UTC, margueriteroth commented
looking into this. THANK U TESTS

2023-01-03 18:54 UTC, margueriteroth commented on src/pages/Content.vue
> -        padding: 0 12.5% 2rem;
Stick to ems for padding, margin, and general sizing. Generally, percentages are only used for flex-basis and mayyyyyyyybe grid things but not really.

2023-01-06 18:07 UTC, margueriteroth commented on src/components/global/RadioGroup.vue
> -      :name="`radio-input-${this.name}`"
`:name="`radio-input-${this.name}`"`

So THIS is the culprit for those failed netlify builds. ^ We cannot reference `this.` in the DOM template since this all gets compiled into static pages. So when that happens, `this` does not exist. Luckily we can just reference the variable normally, so here just `name`. No `this` needed.

I tripped on this hard when making the SSG repo.

2023-01-06 18:10 UTC, margueriteroth commented on src/components/Footer.vue
> +        <MaxWidth class="footer-content" size="m">
This MaxWidth component should help with spacing elements. See the props and spacing. It will take care of the centering and margins.

2023-01-06 18:10 UTC, margueriteroth commented on src/components/Footer.vue
> +    .footer-container {
Make sure all component classes wrap all child styles, so nothing leaks out.

2023-01-06 18:11 UTC, margueriteroth commented on src/components/Footer.vue
> -            grid-template-columns: 40% 10% 1fr;
✂️ %%%%s

2023-01-09 00:58 UTC, sabineloos commented on src/components/Footer.vue
> +        <MaxWidth class="footer-content" size="m">
Ah cool!

2023-01-09 00:58 UTC, sabineloos commented on src/components/Footer.vue
> +    .footer-container {
Oh that makes sense

2023-01-09 01:02 UTC, sabineloos commented on src/pages/Content.vue
> -        padding: 0 12.5% 2rem;
This is really helpful, thanks!

2023-01-23 23:01 UTC, sabineloos requested changes
Hiya! Both Julianne and I looked through this and looks great. I think the only changes would be to remove all the "Dr."s

Thank you SO much. honestly is so much better.

2023-01-23 23:01 UTC, sabineloos commented on src/components/FilterBar.vue
> +                    "all",
NVM Julianne confirmed we can :)

2023-01-23 23:04 UTC, merged